### ISSUE TITLE
BD cell mismatch in tcl script under Vivado 2017.3

### ISSUE THREAD

**Issue by gastor-jojo** [syntacore/fpga-sdk-prj#2]
Hi, 

I am using Vivado 2017.3 design edition under ubuntu 18.04.
After installing the ARTY board files and launching the tcl script, i get the following error on loading BD cells.

```
INFO:` [BD 41-434] Could not find an IP with XCI file by name: system_blk_mem_gen_0_0 
ERROR: [BD 41-1712] The specified IP 'xilinx.com:ip:blk_mem_gen:8.3' does not support the current part 'xc7a35ticsg324-1L'

ERROR: [BD 41-595] Failed to add BD cell <blk_mem_gen_0>
ERROR: [BD 41-425] Failed to read Diagram <system> from BD file </master/fpga/arty/scr1/bd/system/system.bd>
ERROR: [Common 17-39] 'open_bd_design' failed due to earlier errors.
```

Any idea what would be the issue?
(I saw that the tcl header has the mention Vivado 2016.4.
So i installed Vivado 2016.4, but i have the same issue.)

Thanks

**Comment by gastor-jojo** [comment]
solved by modifying arty/scr1/bd/system/system.bd

**Comment by jrive87** [comment]
what did you have to do to the file?
